#!/bin/bash

### Script para a instalação do KDE Neon híbrido a partir do Ubuntu Netboot 20.04
### Por Gustavo Valério Ferreira - www.gustavovalerio.com.br
### Escrito em 18/11/2020 | Atualizada em 20/11/2020
### Use a iso Netboot 20.04
### http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/mini.iso

### Este script instala o KDE Mínimo e mais softwares
### Para quem gostar de um sistema limpo, basta remover
### os softwares escolhidos, tal como os browsers programados.
### O Suporte Netflix/PrimeVideo no Chromium depende do Chrome
### Mas pode ser facilmente corrigo com o mesmo plugin do Brave Browser
### Ou obtido a partir de outra fonte, como o respositório Contrib do Debian, por exemplo.

### O suporte a Flatpak e Snaps é desabilitado.
### O KDE Neon é montado aqui como um sistema Híbrido.
### O repositório User do KDE Neon tem maior preferência.
### Repositórios extras são adicionados para manter outros softwares
### Instalados ou atualizados. Libreoffice/Audacity e Inkscape, por exemplo.
### O Plymouth é removido, por não ser útil. Kernel XanMod é instalado por padrão
### Se não gosta do XanMod, rremova as linhas necessárias, como também o repositório.

### Note que o script é focado em hardware Intel.
### Se seu hardware for diferente, altere as linhas necessárias.
### Minha instalação atual e padrão foi feita de acordo com este script.


### Faça a instalação do Ubuntu Minimal normalmente
### Na hora de escolher as Interfaces do Ubuntu, não marque nada.
### Quando a instalação terminar, restará apenas a tela preta do shell.
### Se seu hardware for Intel, apenas faça login e use o wget para obter:
### wget http://blog.gustavovalerio.com.br/Neon && chmod +x Neon && ./Neon

### Variáveis
readonly WGET="wget -qO -"
readonly KEY="apt-key add -"
readonly INSTALL="apt install --no-install-recommends -y"
readonly PPA="apt-key adv --keyserver keyserver.ubuntu.com --recv-keys"

$INSTALL gnupg   #necessário para adicionar repositórios extras
apt      purge plymouth -y
apt      clean
apt      autoclean
apt      autoremove -y

# Habilitando boot pelo systemd -> Apenas para UEFI
#bootctl install --path=/boot/efi
#bootctl update
#apt purge grub*
#apt autoremove -y
#apt install --reinstall efibootmgr

# Obtendo chaves do kernel e browsers
# Obtendo também a chave do Projeto Neon
$WGET https://dl.xanmod.org/gpg.key | $KEY
$WGET https://deb.opera.com/archive.key | $KEY
$WGET http://archive.neon.kde.org/public.key | $KEY
$WGET https://dl.google.com/linux/linux_signing_key.pub | $KEY

$PPA 36E81C9267FD1383FCC4490983FBA1751378B444 # Chave Libreoffice
$PPA 22C4850146603F3DB0ED00479DA4BD18B9A06DE3 # Chave Inkscape Fresh
$PPA A0062203196CA4482DDB859E4C1CBE14852541CB # Chave UbuntuHandbook - Audacity
$PPA E6AC16572ED1AD6F96C7EBE01E5F8BBC5BEB10AE # Chave System76 - Somente para Chromium

# Kernel XanMod
printf 'deb [arch=amd64] http://deb.xanmod.org releases main' > /etc/apt/sources.list.d/xanmod-kernel.list

# PPAs
printf 'deb [arch=amd64] http://ppa.launchpad.net/libreoffice/ppa/ubuntu focal main' > /etc/apt/sources.list.d/libreoffice.list
printf 'deb [arch=amd64] http://ppa.launchpad.net/inkscape.dev/stable/ubuntu focal main' > /etc/apt/sources.list.d/inkscape.list
printf 'deb [arch=amd64] http://ppa.launchpad.net/system76/pop/ubuntu focal main' > /etc/apt/sources.list.d/chromium-browser.list
printf 'deb [arch=amd64] http://ppa.launchpad.net/ubuntuhandbook1/audacity/ubuntu focal main' > /etc/apt/sources.list.d/audacity.list

# Browsers
printf 'deb [arch=amd64] https://deb.opera.com/opera-stable/ stable non-free' > /etc/apt/sources.list.d/opera-stable.list
printf 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list

# Reorganizando repositórios do Ubuntu
rm -f /etc/apt/sources.list
printf '# Canonical Partners
deb [arch=amd64] http://archive.canonical.com/ubuntu/ focal partner
' > /etc/apt/sources.list.d/canonical-partners.list

printf '# Ubuntu Repos Standards
deb [arch=amd64] http://br.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
' > /etc/apt/sources.list.d/ubuntu-standards.list

printf '# Ubuntu Security
deb [arch=amd64] http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
' > /etc/apt/sources.list.d/ubuntu-security.list

printf '# Ubuntu Repos Standards Updates
deb [arch=amd64] http://br.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
' > /etc/apt/sources.list.d/ubuntu-updates.list

printf '# Ubuntu Backports
deb [arch=amd64] http://br.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
' > /etc/apt/sources.list.d/ubuntu-backports.list

printf '#Neon User
deb [arch=amd64] http://archive.neon.kde.org/user/ focal main
' > /etc/apt/sources.list.d/neon.list

#Adicionando travas

# Impede instalação do Plymouth
printf '
Package: *plymouth*
Pin: release *
Pin-Priority: -1
' > /etc/apt/preferences.d/10-plymouth

# Impede instalação do Packagekit
printf '
Package: packagekit
Pin: release *
Pin-Priority: -1
' > /etc/apt/preferences.d/20-packagekit

# Bloqueando pacotes não-nativos
# Impede instalação de softwares Snaps
printf '
Package: snapd
Pin: release *
Pin-Priority: -1
' > /etc/apt/preferences.d/30-snap

# Impede instalação de softwares Flatpaks
printf '
Package: flatpak
Pin: release *
Pin-Priority: -1
' > /etc/apt/preferences.d/40-flatpak

# Impede instalação do akonadi
printf '
Package: akonadi-server
Pin: release *
Pin-Priority: -1
' > /etc/apt/preferences.d/50-akonadi

# Libera apenas apenas o Chromium do repositório System76/Pop
printf '
Package: *
Pin: release o=LP-PPA-system76-pop
Pin-Priority: -1

Package: *chromium*
Pin: release o=LP-PPA-system76-pop
Pin-Priority: 1100
' > /etc/apt/preferences.d/60-chromium

apt clean
apt autoclean
apt update
apt full-upgrade -y

$INSTALL linux-xanmod intel-microcode iucode-tool ufw python-is-python3 prel{oad,ink}

###KDE Connect
ufw allow 1714:1764/tcp
ufw allow 1714:1764/udp

$INSTALL kde-{spectacle,config-{sddm,gtk-style{,-preview}}}
$INSTALL plasma-{nm,pa,{browser-,}integration,framework,workspace,desktop}
$INSTALL xserver-xorg-{video-intel,core} xinit alsa-base zram-config mesa-utils
$INSTALL firefox{,-locale-pt} {opera,google-chrome}-stable chromium{,-l10n}
$INSTALL okular dolphin{,-plugins} kio-extras sddm synaptic elisa vlc{,-l10n} systemsettings ark
$INSTALL breeze{,-gtk-theme} po{werdevil,lkit-kde-agent-1} libpam-kwallet5 print-manager gwenview
$INSTALL audacity lsp-plugins-vst gimp{,-gmic,-data-extras,-plugin-registry} inkscape mkvtoolnix-gui neon-settings-2
$INSTALL k{menuedit,ate,onsole,win-x11,sysguard,deconnect,infocenter,torrent,screen,denlive,calc,rename,id3-qt,hotkeys,dialog}
$INSTALL winff-qt ffmpeg{,thumbs} vokoscreen libreoffice-{style-sifr,lightproof-pt-br,calc,writer,l10n-pt-br,{kf,qt}5} u{disks2,power} thermald

sed -i 's/memfree = 50/memfree = 100/g'    /etc/preload.conf
sed -i 's/memcached = 0/memcached = 30/g'  /etc/preload.conf
sed -i 's/memcached = 0/memcached = 30/g'  /etc/preload.conf

# Suporte Netflix/PrimeVideo a partir da lib do Chrome
cp -rv /opt/google/chrome/WidevineCdm/ /usr/lib/chromium/
cp -rv /opt/google/chrome/WidevineCdm/ /usr/lib/x86_64-linux-gnu/opera/

cp -v /usr/share/systemd/tmp.mount /etc/systemd/system/
systemctl disable NetworkManager-wait-online.service
systemctl enable tmp.mount upower

ufw enable


### Corrigindo o problema de rede não gerenciável pós-instalação:
mv -v /etc/network/interfaces{,.orig}
printf 'auto lo\niface lo inet loopback' > /etc/network/interfaces

cp -rv /etc/NetworkManager/NetworkManager.conf{,.orig}
sed -i 's/managed=false/managed=true/g' /etc/NetworkManager/NetworkManager.conf

mv -v /etc/netplan{,.orig}/ && mkdir /etc/netplan
printf 'network:\n  version: 2\n  renderer: NetworkManager' > /etc/netplan/01-network-manager-all.yaml

mv -v /etc/default/grub{,.orig}
printf '#Grub Settings
GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash=silent"
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX="mitigations=off loglevel=3 vga=current systemd.show_status=false rd.udev.log_priority=3  libahci.ignore_sss=1"
' > /etc/default/grub

modprobe zram tcp_bbr
prelink -amvR
update-grub
reboot
